### ISSUE TITLE
Sound File Null Pointer Exception

### ISSUE THREAD

**Issue by maccopacco** [FRCTeam871/RoboticsSimulator2018#13]
`
C:\Users\maxdr\Desktop\roboSim-1.0.0-beta\roboSim-1.0.0-beta\server>java -jar server.jar
Started server successfully.
false 50001
[Robotics Simulator 2018] [INFO] Starting sound system...
[Robotics Simulator 2018] [INFO] Started TinySound System!
[Robotics Simulator 2018] [INFO] Loading config...
[Robotics Simulator 2018] [WARN] Error loading config: The system cannot find the path specified
java.io.IOException: The system cannot find the path specified
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at me.pieking.game.Settings.loadConfig(Settings.java:64)
        at me.pieking.game.Game.init(Game.java:300)
        at me.pieking.game.Game.run(Game.java:119)
        at me.pieking.game.Game.runGame(Game.java:111)
        at me.pieking.game.net.ServerStarter.lambda$0(ServerStarter.java:70)
        at java.lang.Thread.run(Thread.java:748)
[Robotics Simulator 2018] [INFO] Done!
POWER_CUBE collides with SHIP
POWER_CUBE collides with POWER_CUBE
POWER_CUBE collides with SCALE_PLATFORM
POWER_CUBE collides with SWITCH_PLATFORM
POWER_CUBE collides with POWER_CUBE_HOLDING_GROUND
POWER_CUBE_HOLDING_GROUND collides with SHIP
POWER_CUBE_HOLDING_GROUND collides with POWER_CUBE
POWER_CUBE_HOLDING_GROUND collides with SCALE_PLATFORM
POWER_CUBE_HOLDING_GROUND collides with SWITCH_PLATFORM
POWER_CUBE_HOLDING_GROUND collides with POWER_CUBE_HOLDING_GROUND
POWER_CUBE_HOLDING_LOW collides with SHIP
POWER_CUBE_HOLDING_LOW collides with SCALE_PLATFORM
POWER_CUBE_HOLDING_HIGH collides with SHIP
SHIP collides with SHIP
SHIP collides with POWER_CUBE
SHIP collides with SCALE_PLATFORM
SHIP collides with SWITCH_PLATFORM
SCALE_PLATFORM_CENTER collides with SHIP
SCALE_PLATFORM_CENTER collides with POWER_CUBE_HOLDING_GROUND
SCALE_PLATFORM_CENTER collides with POWER_CUBE_HOLDING_LOW
SCALE_PLATFORM collides with SHIP
SCALE_PLATFORM collides with POWER_CUBE
SCALE_PLATFORM collides with POWER_CUBE_HOLDING_GROUND
SCALE_PLATFORM collides with POWER_CUBE_HOLDING_LOW
SWITCH_PLATFORM_CENTER collides with SHIP
SWITCH_PLATFORM_CENTER collides with POWER_CUBE_HOLDING_GROUND
SWITCH_PLATFORM collides with SHIP
SWITCH_PLATFORM collides with POWER_CUBE
SWITCH_PLATFORM collides with POWER_CUBE_HOLDING_GROUND
Match End_normalized.wav file:/C:/Users/maxdr/Desktop/robo2018/sound/Match%20End_normalized.wav
Resources.getSound(Match End_normalized.wav) == file:/C:/Users/maxdr/Desktop/robo2018/sound/Match%20End_normalized.wav
C:\Users\maxdr\Desktop\robo2018\sound\Match End_normalized.wav false
Error getting resource stream!
C:\Users\maxdr\Desktop\robo2018\sound\Match End_normalized.wav (The system cannot find the path specified)
file:/C:/Users/maxdr/Desktop/robo2018/sound/Match%20End_normalized.wav null
Exception in thread "Thread-0" java.lang.ExceptionInInitializerError
        at me.pieking.game.Game.init(Game.java:303)
        at me.pieking.game.Game.run(Game.java:119)
        at me.pieking.game.Game.runGame(Game.java:111)
        at me.pieking.game.net.ServerStarter.lambda$0(ServerStarter.java:70)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at me.pieking.game.sound.TinySoundClip.<init>(TinySoundClip.java:26)
        at me.pieking.game.sound.TinySoundSystem.loadSound(TinySoundSystem.java:48)
        at me.pieking.game.sound.Sound.loadSound(Sound.java:153)
        at me.pieking.game.Gameplay.<clinit>(Gameplay.java:40)
        ... 5 more
`

**Comment by t3pfaffe** [comment]
ok. Make sure it is on desktop. The folder has to be on the desktop
